---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on: [push, pull_request]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get install -qqy --no-install-recommends \
            python3-venv python3-setuptools
          python3 -m venv .venv
          .venv/bin/python3 -m pip install -U pip
          if [ -f requirements.txt ]
          then .venv/bin/python3 -m pip install -r requirements.txt
          fi
          mv .venv /home/runner/work/_temp/_github_workflow

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://github/super-linter:v3
        env:
          PYTHONPATH:
            '/github/workspace:/github/workflow/.venv/lib/python3.6/site-packages'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
