name: MarkdownLint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install markdownlint-cli
      run: sudo npm install --global markdownlint-cli

    - run: markdownlint .
