---

name: YamlLint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install yamllint
        run: sudo -H pip install yamllint

      - run: yamllint .
